<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Advice rule</name>
  <uuid>bf3e9fee-31b5-4ad7-80eb-ae3f348db844</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[if
    Name is defined
then
    set decision to a new response where the message is `Hello { 'Name' }! { 'Weather advice' }` ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
